// Pure Node PowerPoint generator (pptxgenjs) — no Python dependency.
'use strict';
const fs = require('fs');
const path = require('path');
const PptxGenJS = require('pptxgenjs');

const THEMES = {
  professional: { bg: 'FFFFFF', title: '1F3864', text: '333333', accent: '2E74B5' },
  modern: { bg: 'F5F5F5', title: '111827', text: '374151', accent: '6366F1' },
  creative: { bg: 'FFF7ED', title: '9A3412', text: '431407', accent: 'EA580C' },
  minimal: { bg: 'FFFFFF', title: '000000', text: '444444', accent: '000000' },
  dark: { bg: '0F172A', title: 'F8FAFC', text: 'CBD5E1', accent: '38BDF8' },
};

async function createPowerPoint(payload = {}) {
  const { file_path, title, slides = [], theme } = payload;
  if (!file_path) return { success: false, message: 'file_path is required' };

  const colors = THEMES[theme] || THEMES.professional;

  try {
    fs.mkdirSync(path.dirname(file_path), { recursive: true });

    const pptx = new PptxGenJS();
    pptx.defineLayout({ name: 'ALSA', width: 10, height: 5.63 });
    pptx.layout = 'ALSA';

    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: colors.bg };
    titleSlide.addText(title || 'Untitled Presentation', {
      x: 0.5, y: 2.0, w: 9, h: 1.5,
      fontSize: 40, bold: true, color: colors.title, align: 'center',
    });
    titleSlide.addText('Generated by Alsa AI', {
      x: 0.5, y: 3.4, w: 9, h: 0.5,
      fontSize: 16, color: colors.accent, align: 'center',
    });

    for (const s of slides) {
      const slide = pptx.addSlide();
      slide.background = { color: colors.bg };
      slide.addText(s.title || '', {
        x: 0.5, y: 0.35, w: 9, h: 0.8,
        fontSize: 28, bold: true, color: colors.title,
      });

      const content = String(s.content || '');
      const lines = content.split('\n').filter(Boolean);

      if (s.layout === 'two_column') {
        const mid = Math.ceil(lines.length / 2);
        slide.addText(
          lines.slice(0, mid).map((l) => ({ text: l, options: { bullet: true, breakLine: true } })),
          { x: 0.5, y: 1.3, w: 4.3, h: 3.8, fontSize: 16, color: colors.text }
        );
        slide.addText(
          lines.slice(mid).map((l) => ({ text: l, options: { bullet: true, breakLine: true } })),
          { x: 5.2, y: 1.3, w: 4.3, h: 3.8, fontSize: 16, color: colors.text }
        );
      } else {
        const textRuns = lines.length > 1
          ? lines.map((l) => ({ text: l, options: { bullet: true, breakLine: true } }))
          : content;
        slide.addText(textRuns, { x: 0.5, y: 1.3, w: 9, h: 3.8, fontSize: 18, color: colors.text });
      }
    }

    await pptx.writeFile({ fileName: file_path });
    return { success: true, message: `PowerPoint created with ${slides.length + 1} slides`, file_path };
  } catch (err) {
    return { success: false, message: err.message || 'Failed to create PowerPoint' };
  }
}

module.exports = { createPowerPoint };

if (require.main === module) {
  const payload = JSON.parse(process.argv[2] || '{}');
  createPowerPoint(payload).then((r) => {
    console.log(JSON.stringify(r));
    process.exitCode = r.success ? 0 : 1;
  });
}
